version: 2
updates:
  - package-ecosystem: "npm"
    directory: "./application"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "./drawer"
    schedule:
      interval: "weekly"
